# you can change the labels to suit your needs if "first-timers-only" is not what you are looking for.
# These are some examples.
labels:
  - foo
  - bar

#If you would like to add your own template for the issue, add an .md file to your .github folder
template: .github/first-timers-issue-template.md 

repository: sandbox2
