name: Merge Schedule

on: 
  pull_request:
    types: 
      - opened
      - edited

jobs:
  set_status:
    runs-on: ubuntu-latest

    steps:
      - uses: octokit/request-action@v2.x
        id: create_check_run
        with:
          route: POST /repos/:repository/check-runs
          repository: ${{ github.repository }}
          mediaType: '{"previews": ["antiope"]}'
          name: "schedule"
          head_sha: ${{ github.sha }}
          status: in_progress
          output: '{"title":"Test check run title","summary": "A summary of the test check run"}'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
