name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    # https://crontab.guru/every-five-minutes
    - cron: */5 * * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@initial-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
